# Generated by Django 5.0 on 2024-01-05 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_remove_category_user_categoryuser"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(model_name="categoryuser", name="category",),
        migrations.AddField(
            model_name="categoryuser",
            name="categories",
            field=models.ManyToManyField(to="categories.category"),
        ),
        migrations.AlterField(
            model_name="categoryuser",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
