# Generated by Django 5.0 on 2024-01-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userexpense_userincome"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userincome",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
