# Generated by Django 5.0 on 2024-01-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_userincome_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userexpense",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
